name: tests-backend
on: [pull_request]

jobs:
  tests-backend:
    name: tests-backend
    runs-on: Linux

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: backend/app/.venv
          key: ${{ runner.os }}-python-${{ hashFiles('backend/app/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Create empty .env file
        run: touch .env

      - name: Install dependencies
        run: |
          make env-create

      - name: Run tests
        run: |
          . backend/app/.venv/bin/activate && make test
